
# Part V: Basic Data Visualization (20 minutes) {-}


## Creating simple plots using plot() {-}

```{r}
# Example: Simple scatter plot
x <- 1:10
y <- rnorm(10)
plot(x, y, main = "Simple Scatter Plot", xlab = "X Axis", ylab = "Y Axis", col = "blue")

```

## Creating more complex plots ggplot() {-}

```{r}
# Installing and loading ggplot2 package
# install.packages("ggplot2")
library(ggplot2)

# Example: Complex scatter plot with ggplot2
ggplot(data.frame(x, y), aes(x, y)) + geom_point() + 
  ggtitle("Complex Scatter Plot with ggplot2") +
  xlab("X Axis") + ylab("Y Axis")
```

## Creating plots with other library {-}
```{r}
# Installing and loading the lattice package
# install.packages("lattice")
library(lattice)

# Example: Lattice plot
xyplot(y ~ x, data = data.frame(x, y), main = "Lattice Plot", type = "p")


```

## Creating demographic, map, 3d plots {-}

```{r}
# Installing and loading plotly for 3D plots
#install.packages("plotly")
library(plotly)

# Example: 3D Scatter Plot with plotly
plot_ly(data.frame(x, y, z = rnorm(10)), x = ~x, y = ~y, z = ~z, type = "scatter3d", mode = "markers")

# Installing and loading maps package for map plots
#install.packages("maps")
library(maps)

# Example: Map plot
map("world", fill = TRUE, col = "#D3D3D3", border = "white", xlim = c(-130, -60), ylim = c(20, 50))
```

```{r}
# --- Part V: Basic Data Visualization (20 minutes) ---

# Creating a 3D surface plot with plotly

# Installing and loading plotly package
# install.packages("plotly")
library(plotly)

# Simulating a surface for a function (e.g., Rosenbrock function)
rosenbrock <- function(x, y) { (1 - x)^2 + 100 * (y - x^2)^2 }
x <- seq(-2, 2, length.out = 50)
y <- seq(-1, 3, length.out = 50)
z <- outer(x, y, rosenbrock)

# Example: 3D Surface Plot
plot_ly(x = ~x, y = ~y, z = ~z, type = "surface", 
        contours = list(z = list(show = TRUE, usecolormap = TRUE, highlightcolor = "#ff0000", project = list(z = TRUE))))

```
